### ISSUE TITLE
03_interface_properties

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#13]
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function interface_properties in module basics.interface_properties

interface_properties(device_name, interface_name)
    Return a named tuple containing the information available for the specified interface of the specified, mounted device.

https://198.18.1.25/controller/restconf/operational/opendaylight-inventory:nodes
https://198.18.1.25/controller/restconf/config/opendaylight-inventory:nodes/node/controller-config/yang-ext:mount/config:modules/module/odl-sal-netconf-connector-cfg:sal-netconf-connector/por
https://198.18.1.25/controller/restconf/config/opendaylight-inventory:nodes/node/por/yang-ext:mount/Cisco-IOS-XR-ifmgr-cfg:interface-configurations
https://198.18.1.25/controller/restconf/operational/opendaylight-inventory:nodes/node/por/yang-ext:mount/Cisco-IOS-XR-ifmgr-oper:interface-properties
interface_properties(por, GigabitEthernet0/0/0/2)
https://198.18.1.25/controller/restconf/operational/opendaylight-inventory:nodes/node/por/yang-ext:mount/Cisco-IOS-XR-ifmgr-oper:interface-properties/data-nodes/data-node/0%2F0%2FCPU0/system-view/interfaces/interface/GigabitEthernet0%2F0%2F0%2F2
Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_properties.py", line 52, in <module>
    main()
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_properties.py", line 48, in main
    return demonstrate(device_name, interface_name)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_properties.py", line 37, in demonstrate
    print_rich(interface_properties(device_name, interface_name))
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/interface_properties.py", line 114, in interface_properties
    response = odl_http_get(url, 'application/xml')
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 139, in odl_http_get
    return odl_http_request('get', url_suffix, contentType, content, accept, expected_status_code)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/odl_http.py", line 111, in odl_http_request
    raise Exception(msg)
Exception: Expected HTTP status code 200, got 404, "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /controller/restconf/operational/opendaylight-inventory:nodes/node/por/yang-ext:mount/Cisco-IOS-XR-ifmgr-oper:interface-properties/data-nodes/data-node/0/0/CPU0/system-view/interfaces/interface/GigabitEthernet0/0/0/2 was not found on this server.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at 198.18.1.25 Port 443</address>
</body></html>
"

**Comment by kjarrad** [comment]
This is a symptom of issue #15 which is not yet closed but we have implemented a workaround until COSC is fixed so *this* issue is closed.
