### ISSUE TITLE
Formatting issues with 03_interface_configuration_update Python 2.7

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#20]
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_update in module basics.interface

interface_configuration_update(device_name, interface_name, description, address, netmask, active=u'act', shutdown=False)
    Update the configuration of the specified interface of the specified device.
    
    The outcome is undefined if the specified device is not connected.

Initial configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description=None, shutdown=False, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Modify configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, Mutable, 101.101.101.101, 255.255.0.0, True)

Restore configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, None, 54.0.0.26, 255.255.255.0, False)
Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_configuration_update.py", line 90, in <module>
    sys_exit(main())
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_configuration_update.py", line 84, in main
    demonstrate(device_name, interface_config)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_configuration_update.py", line 61, in demonstrate
    interface_configuration_update(device_name, initial.name, description=initial.description, address=initial.address, netmask=initial.netmask, shutdown=initial.shutdown)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/interface.py", line 246, in interface_configuration_update
    url_suffix = _configuration_multi_url_template % (device_name, active, quote_plus(interface_name))
TypeError: not all arguments converted during string formatting

**Comment by kjarrad** [comment]
Fixed and if there is a problem then it is due to issue #24 so close this issue. Here is stdout:
```
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_update in module basics.interface

interface_configuration_update(device_name, interface_name, description, address, netmask, active=u'act', shutdown=False)
    Update the configuration of the specified interface of the specified device.
    
    The outcome is undefined if the specified device is not connected.

Initial configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description='None', shutdown=True, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Modify configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, Mutable, 101.101.101.101, 255.255.0.0, False)

Modified configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description='Mutable', shutdown=False, address='101.101.101.101', netmask='255.255.0.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Restore configuration:
interface_configuration_update(por, GigabitEthernet0/0/0/2, None, 54.0.0.26, 255.255.255.0, True)

Restored configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description='None', shutdown=True, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')
```
