### ISSUE TITLE
Why do we have 03_interface_configuration and 03_interface_properties?

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#21]
It seems that the interface_configuration_tuple function in 03_interface_configuration provides a subset of the configuration properties from interface_properties in 03_interface_properties.

It is not clear why need both functions. 

It also seems that the interface_properties function should be called interface_properties_tuple to be consistent?

**Comment by kjarrad** [comment]
1. properties and configuration are different. It is easier to see the difference when the output are nicely tabulated in html.
2. agree that convergence of names would be more consistent. Need to do this for everything inside file interface.py.
3. move content of interface_properties.py into interface.py

**Comment by kjarrad** [comment]
Properties are operational state.
Configuration can be modified by end user.
