### ISSUE TITLE
Formatting issue with 03_interface_shutdown Python 2.7

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#22]
cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_update in module basics.interface

interface_configuration_update(device_name, interface_name, description, address, netmask, active=u'act', shutdown=False)
    Update the configuration of the specified interface of the specified device.
    
    The outcome is undefined if the specified device is not connected.

Initial configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/2', description=None, shutdown=False, address='54.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Shutdown interface GigabitEthernet0/0/0/2 on por:
interface_configuration_update(por, GigabitEthernet0/0/0/2, None, 54.0.0.26, 255.255.255.0, True)
Traceback (most recent call last):
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_shutdown.py", line 72, in <module>
    sys_exit(main())
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_shutdown.py", line 66, in main
    demonstrate(device_name, interface_config)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/learning_lab/03_interface_shutdown.py", line 46, in demonstrate
    address=initial.address, netmask=initial.netmask, shutdown=shutdown)
  File "/Users/nsowatsk/git/cosc-learning-labs/src/basics/interface.py", line 246, in interface_configuration_update
    url_suffix = _configuration_multi_url_template % (device_name, active, quote_plus(interface_name))
TypeError: not all arguments converted during string formatting

**Comment by kjarrad** [comment]
Fixed. Here is the stdout:
```
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function interface_configuration_update in module basics.interface

interface_configuration_update(device_name, interface_name, description, address, netmask, active=u'act', shutdown=False)
    Update the configuration of the specified interface of the specified device.
    
    The outcome is undefined if the specified device is not connected.

Initial configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/1', description=None, shutdown=False, address='53.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')

Shutdown interface GigabitEthernet0/0/0/1 on por:
interface_configuration_update(por, GigabitEthernet0/0/0/1, None, 53.0.0.26, 255.255.255.0, True)

Modified configuration:
InterfaceConfiguration(name='GigabitEthernet0/0/0/1', description='None', shutdown=True, address='53.0.0.26', netmask='255.255.255.0', packet_filter_outbound=None, packet_filter_inbound=None, active='act')
```
