### ISSUE TITLE
01_inventory - Unclear what is, or is not, in inventory

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#26]
When running 01_inventory.py, we get the text below.  

"The inventory includes all mounted devices.
The inventory excludes all unmounted devices.
The inventory can contain devices that are neither mounted nor unmounted.
..."

If the inventory, as in line 2, excludes unmounted devices, then what does line 3 mean?

See full output below.

cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   username = admin
   scope = sdn
   password = cisco123
   grant_type = password
cosc authentication status code: 201
Python Library Documentation: function inventory in module basics.inventory

inventory()
    Names of network devices known to the Controller.
    
    The inventory includes all mounted devices.
    The inventory excludes all unmounted devices.
    The inventory can contain devices that are neither mounted nor unmounted.
    The inventory includes all connected devices.
    The inventory can contain unconnected devices.
    Returns a list.

['openflow:1', 'por', 'openflow:6', 'openflow:7', 'openflow:4', 'openflow:5', 'lax', 'openflow:2', 'openflow:3', 'sjc', 'sfc', 'grox', 'min', 'sea', 'san', 'kcy']

**Comment by kjarrad** [comment]
The inventory can contain devices that are introduced independently of the
    Controller's mounting process. 
    Examples of these devices are Open Flow switches.
    Such devices have the following characteristics:
    - not considered to be 'mounted' (see fn 'inventory_mounted')
    - no 'control' information available (see fn 'inventory_control')
    - not considered to be 'unmounted' because there are no settings configured
    - cannot be mounted (because not unmounted)
    - cannot be dismounted (because not mounted)
