### ISSUE TITLE
04_story refers to scripts that do not appear to be there

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#29]
The comment in 04_story has:

The basic story would be:
        04_static_route_create_port_grant
        04_static_route_apply_packet_filter
        04_static_route_unapply_packet_filter

But those scripts appear not to exist?

**Comment by kjarrad** [comment]
04_story was copy-and-paste from 05_acl and the comment is incorrect - it is the outcome of search-and-replace 'acl' with 'static_route'.
