### ISSUE TITLE
04_routes.py needs some form of "pretty printing"

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#30]
$ ./04_routes.py
cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
('routes', {u'tables': [{u'attributes': {u'uptodate': True}, u'bgp-linkstate:linkstate-routes': {u'linkstate-route': [{u'ip-reachability-information': u'56.0.0.0/24', u'protocol-id': u'isis-level2', u'attributes': {u'origin': {u'value': u'igp'}, u'local-pref': {u'pref': 100}, u'prefix-attributes': {u'prefix-metric': 10}, u'as-path': {}}, u'identifier': 0, u'route-key': u'AAMALwIAAAAAAAAAAAEAABoCAAAEAAD/4AIBAAQeHh4eAgMABgAAAAAAMAEJAAQYOAAA', u'advertising-node-descriptors': {u'domain-id': 505290270, u'as-number': 65504, u'isis-node': {u'iso-system-id': u'AAAAAAAw'}}},... and on and on in an unreadable blob of text :-)

**Comment by kjarrad** [comment]
I applied JSON pretty print to the routes data and updated the MarkDown documentation.
