### ISSUE TITLE
./04_static_route_json_all.py Shows "interface-name": "Null0"

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#38]
./04_static_route_json_all.py 
cosc authentication url: https://198.18.1.25/controller-auth
...
cosc authentication status code: 201
Python Library Documentation: function static_route_json_all in module basics.routes

static_route_json_all(device_name)
    All static routes on the specified network device.

static_route_json_all(por)
[
  {
    "prefix": "11.11.4.0", 
    "prefix-length": 24, 
    "vrf-route": {
      "vrf-next-hops": {
        "interface-name": [
          {
            "interface-name": "Null0"
          }
        ]
      }
    }
  }
]

**Comment by kjarrad** [comment]
04_static_route_json_all.py was folded into 04_static_route_json.py, which now performs two separate but related demonstrations.
