### ISSUE TITLE
04_topology Expect url_params to be <class 'dict'>, got <class 'str'>

### ISSUE THREAD

**Issue by NathanCisco** [CiscoDevNet/cosc-learning-labs#41]
cosc authentication url: https://198.18.1.25/controller-auth
cosc authentication parameters:
   password = cisco123
   grant_type = password
   scope = sdn
   username = admin
cosc authentication status code: 201
Python Library Documentation: function topology in module basics.topology

topology(config)
    Return the NETCONF topology JSON format.
    
    The topology should be the only topology in the list.
    The topology includes all mounted devices.
    The topology excludes all unmounted devices.
    The topology can contain devices that are neither mounted nor unmounted.
    The topology includes all connected devices.
    The topology can contain unconnected devices.

Expect url_params to be <class 'dict'>, got <class 'str'>

**Comment by kjarrad** [comment]
Need Lithium for this URL to work (I think). Currently get 404, which is reasonable for Helium.
