### ISSUE TITLE
02_capability.py shows no capabilities for Devices

### ISSUE THREAD

**Issue by brtiller1** [CiscoDevNet/cosc-learning-labs#61]
In the Ubuntu server the devices are mounted as shown 01_inventory_mounted.py, but the 02_capability.py script returns no capabilities and does not match expected output in Learning Lab for the devices.

cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$ ./01_inventory_mounted.py
Python Library Documentation: function inventory_mounted in module basics.inventory

inventory_mounted()
    Names of network devices mounted on the Controller.

    Output a list of names.
    Mounted devices are a subset of the inventory.
    Mounted devices can be connected or not.

['sjc', 'por', 'sfc', 'min', 'sea', 'san', 'lax', 'kcy']
cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$ ./02_capability.py
cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$

**Comment by brtiller1** [comment]
Capability discovery script shows no caps as well.

cisco@ubuntu:~/git/cosc-learning-labs/src/learning_lab$ ./02_capability_discovery.py

capability_discovery(Cisco-IOS-XR-ipv4-acl-cfg, http://cisco.com/ns/yang/):
         None

capability_discovery(Cisco-IOS-XR-ip-static-cfg, http://cisco.com/ns/yang/):
         None

capability_discovery(not_available_yet, coming_soon):
         None

**Comment by kjarrad** [comment]
This problem may be resolved by waiting for the controller to establish connections with the network devices. 

Please reproduce the problem, substituting script 01_inventory_connected for 01_inventory_mounted.

It may be appropriate for the sample script to output a brief message when there is otherwise no output.

**Comment by kjarrad** [comment]
I have added an explicit message when there are no capable devices.

**Comment by kjarrad** [comment]
My previous sample output was from a different sample script (02_capability_discovery.py)

**Comment by kjarrad** [comment]
Renamed 02_capability to 02_device_capability

Output when no devices are available:

Demonstrate how to discover the capability of one network device.

The following demonstrations are performed:
1. Determine the inventory of network devices and choose one.
2. Discover all capabilities of the chosen network device.

1. Determine the inventory of network devices and choose one.
inventory_mounted()
There are no mounted network devices. Demonstration cancelled.
