### ISSUE TITLE
Remove Step 4 Interfaces text from Step 5 of Learning Lab

### ISSUE THREAD

**Issue by brtiller1** [CiscoDevNet/cosc-learning-labs#62]
The bottom of the Step 5 page at https://learninglabs.cisco.com/lab/cosc/step/5 has text "Step 4 Interfaces" which should not be there.  Please remove.

**Comment by kjarrad** [comment]
Updated file:
https://github.com/CiscoDevNet/cosc-learning-labs/blob/master/doc/guide/Learning-Lab/5.md

Not sure of the process to send the updated file to the DevNet web server.
