### ISSUE TITLE
03_interface_names and 03_interface_configuration  not giving the expected result 

### ISSUE THREAD

**Issue by Geevarghese** [CiscoDevNet/cosc-learning-labs#74]
--------------- O/p -------------------------------
Python Library Documentation: function interface_names in module basics.interface

interface_names(device_name)
    Return a list of interface names, given the name of a mounted, connected device.

There are no mounted, connected devices to examine. Demonstration cancelled
--------------------- O/P -------------------
Python Library Documentation: function interface_configuration_tuple in module basics.interface

interface_configuration_tuple(device_name, interface_name=None)
    Return a named tuple containing the configuration information for the specified interface of the specified, mounted device.

interface_configuration(por, GigabitEthernet0/0/0/2)
InterfaceConfiguration
name    value
------  -------
-------------------------------------

**Comment by kjarrad** [comment]
I get the following output
```
Python Library Documentation: function interface_configuration_tuple in module basics.interface

interface_configuration_tuple(device_name, interface_name=None)
    Return a named tuple containing the configuration information for the specified interface of the specified, mounted device.

interface_configuration(por, GigabitEthernet0/0/0/2)
InterfaceConfiguration
name                    value
----------------------  ----------------------
name                    GigabitEthernet0/0/0/2
description
shutdown                False
address                 54.0.0.26
netmask                 255.255.255.0
packet_filter_outbound
packet_filter_inbound
active                  act
```

Geevarghese, could you please paste your text output inside block quotes so that we can compare.

**Comment by Geevarghese** [comment]
![int_config](https://cloud.githubusercontent.com/assets/10231479/8222981/6bd8cf82-1590-11e5-904e-c7492a1ec862.jpg)

**Comment by Geevarghese** [comment]
For 03_interface_names got the correct output . yesterday it was not showing

![image](https://cloud.githubusercontent.com/assets/10231479/8223069/2dcf7410-1591-11e5-99b9-f24fb0ccd6ac.png)

**Comment by Geevarghese** [comment]
After getting the print_table issue fixed was able to get the correct output. So closing the issue.
Thanks a lot Ken for the guidance.
