### ISSUE TITLE
01_device_control.py also not getting value populated

### ISSUE THREAD

**Issue by Geevarghese** [CiscoDevNet/cosc-learning-labs#76]
![image](https://cloud.githubusercontent.com/assets/10231479/8225124/44905332-15ae-11e5-8f5a-959716dbe521.png)

**Comment by kjarrad** [comment]
This is the output I see:
```
Python Library Documentation: function device_control in module basics.inventory

device_control(device_name)
    A DeviceControl if the specified device is mounted, otherwise None.

DeviceControl fields:
	device_name
	address
	port
	username
	password

device_control(kcy)
DeviceControl
name         value
-----------  -----------
device_name  kcy
address      198.18.1.50
port         830
username     cisco
password     cisco
```

**Comment by kjarrad** [comment]
Geeverghese, can you please run another script that also prints similar tables, such as 00_controller.py. That will inform us whether or not the problem is in the print_table function. Make sure you 'git pull' the latest code.
Here is the output I see:
```
ControllerCoordinates
name        value
----------  ----------------------------------------
url_prefix  https://198.18.1.25/controller/restconf/
username    token
password    03b89f28-310e-35ff-b6fd-61177fea3284

Connecting...
name         value
-----------  --------------------------------------------------------------------------------
status       OK
url          https://198.18.1.25/controller/restconf/operational/opendaylight-inventory:nodes
status code  200
method       HEAD
```

**Comment by Geevarghese** [comment]
![controller](https://cloud.githubusercontent.com/assets/10231479/8225792/533fba32-15b6-11e5-8dd4-ecf76181551f.jpg)

**Comment by Geevarghese** [comment]
Hi Ken,
Iam using the dcloud lab session assigned by you yesterday and have cloned the latest code yesterday.
Thanks 
Geevarghese

**Comment by Geevarghese** [comment]
The output of 02_capability_discovery 
![capability](https://cloud.githubusercontent.com/assets/10231479/8225970/1c12879a-15b8-11e5-85c4-65f05526aae0.jpg)

**Comment by Geevarghese** [comment]
Hi Ken ,

  There seems to be difference in the code (capability for which you have made latest changes) which iam running and that is available on the github. So iam not using the latest code. I haven't used git pull instead used the git clone. Will try git pull and confirm both the codes are same and  then will try and  close the issue.

Thanks and Regards,
Geevarghese

**Comment by Geevarghese** [comment]
Hi Ken,
  The values are not getting printed in table format. Trying for that. Attached the result. 
![print_table](https://cloud.githubusercontent.com/assets/10231479/8253139/599be4f6-16aa-11e5-81af-bef684ae8475.jpg)

**Comment by Geevarghese** [comment]
Got the correct output as per the guidance from ken and updating to the latest files using git pull command . So closing the issue.
Thanks and Regards,
Geevarghese
