### ISSUE TITLE
ODL BGP feature enable/disable

### ISSUE THREAD

**Issue by kjarrad** [CiscoDevNet/cosc-learning-labs#88]
Ken> ODL has BGP features that can be installed. ODL communicates using the BGP protocol on ASN 64496.
Giles>  yup. we can either use 41-bgp-example.xml file or RESTCONF to set that up

Ken> If ODL can be instructed via Restconf to enable/disable BGP features then a sample script would capture that knowledge/technique. Giles, do you have a curl or postman that does it?

**Comment by gilesheron** [comment]
already in the postman collection I posted recently.
